<?php namespace App\Database\Seeds;

class RuleSeeder extends \CodeIgniter\Database\Seeder
{
    static $data = [
        ['id_Penyakit'=>'1',  'cf'=>'0.9', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'1',  'cf'=>'0.2', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'1',  'cf'=>'0.8', 'id_Gejala'=> '3'],
        ['id_Penyakit'=>'1',  'cf'=>'0.3', 'id_Gejala'=> '5'],
        ['id_Penyakit'=>'1',  'cf'=>'0.7', 'id_Gejala'=> '9'],
        ['id_Penyakit'=>'1',  'cf'=>'0.9', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'1',  'cf'=>'0.5', 'id_Gejala'=> '18'],
        ['id_Penyakit'=>'2',  'cf'=>'0.3', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'2',  'cf'=>'0.5', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'2',  'cf'=>'0.7', 'id_Gejala'=> '3'],
        ['id_Penyakit'=>'2',  'cf'=>'0.8', 'id_Gejala'=> '4'],
        ['id_Penyakit'=>'2',  'cf'=>'0.7', 'id_Gejala'=> '9'],
        ['id_Penyakit'=>'2',  'cf'=>'0.5', 'id_Gejala'=> '16'],
        ['id_Penyakit'=>'3',  'cf'=>'0.8', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'3',  'cf'=>'0.5', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'3',  'cf'=>'0.9', 'id_Gejala'=> '4'],
        ['id_Penyakit'=>'3',  'cf'=>'0.7', 'id_Gejala'=> '6'],
        ['id_Penyakit'=>'3',  'cf'=>'0.8', 'id_Gejala'=> '12'],
        ['id_Penyakit'=>'3',  'cf'=>'0.6', 'id_Gejala'=> '16'],
        ['id_Penyakit'=>'3',  'cf'=>'0.7', 'id_Gejala'=> '17'],
        ['id_Penyakit'=>'3',  'cf'=>'0.5', 'id_Gejala'=> '20'],
        ['id_Penyakit'=>'4',  'cf'=>'0.8', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'4',  'cf'=>'0.6', 'id_Gejala'=> '6'],
        ['id_Penyakit'=>'4',  'cf'=>'0.8', 'id_Gejala'=> '8'],
        ['id_Penyakit'=>'4',  'cf'=>'0.7', 'id_Gejala'=> '11'],
        ['id_Penyakit'=>'4',  'cf'=>'0.4', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'4',  'cf'=>'0.5', 'id_Gejala'=> '18'],
        ['id_Penyakit'=>'5',  'cf'=>'0.4', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'5',  'cf'=>'0.3', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'5',  'cf'=>'0.9', 'id_Gejala'=> '5'],
        ['id_Penyakit'=>'5',  'cf'=>'0.7', 'id_Gejala'=> '10'],
        ['id_Penyakit'=>'5',  'cf'=>'0.5', 'id_Gejala'=> '14'],
        ['id_Penyakit'=>'5',  'cf'=>'0.9', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'5',  'cf'=>'0.7', 'id_Gejala'=> '16'],
        ['id_Penyakit'=>'5',  'cf'=>'0.7', 'id_Gejala'=> '19'],
        ['id_Penyakit'=>'6',  'cf'=>'0.4', 'id_Gejala'=> '4'],
        ['id_Penyakit'=>'6',  'cf'=>'0.6', 'id_Gejala'=> '7'],
        ['id_Penyakit'=>'6',  'cf'=>'0.5', 'id_Gejala'=> '13'],
        ['id_Penyakit'=>'6',  'cf'=>'0.4', 'id_Gejala'=> '14'],
        ['id_Penyakit'=>'6',  'cf'=>'0.8', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'6',  'cf'=>'0.9', 'id_Gejala'=> '16'],
        ['id_Penyakit'=>'6',  'cf'=>'0.4', 'id_Gejala'=> '19'],
        ['id_Penyakit'=>'7',  'cf'=>'0.3', 'id_Gejala'=> '6'],
        ['id_Penyakit'=>'7',  'cf'=>'0.9', 'id_Gejala'=> '12'],
        ['id_Penyakit'=>'7',  'cf'=>'0.7', 'id_Gejala'=> '13'],
        ['id_Penyakit'=>'7',  'cf'=>'0.6', 'id_Gejala'=> '14'],
        ['id_Penyakit'=>'7',  'cf'=>'0.8', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'7',  'cf'=>'0.6', 'id_Gejala'=> '18'],
        ['id_Penyakit'=>'7',  'cf'=>'0.8', 'id_Gejala'=> '20'],
        ['id_Penyakit'=>'8',  'cf'=>'0.6', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'8',  'cf'=>'0.4', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'8',  'cf'=>'0.5', 'id_Gejala'=> '3'],
        ['id_Penyakit'=>'8',  'cf'=>'0.1', 'id_Gejala'=> '4'],
        ['id_Penyakit'=>'8',  'cf'=>'0.2', 'id_Gejala'=> '5'],
        ['id_Penyakit'=>'8',  'cf'=>'0.4', 'id_Gejala'=> '6'],
        ['id_Penyakit'=>'8',  'cf'=>'0.9', 'id_Gejala'=> '9'],
        ['id_Penyakit'=>'8',  'cf'=>'0.8', 'id_Gejala'=> '15'],
        ['id_Penyakit'=>'8',  'cf'=>'0.7', 'id_Gejala'=> '18'],
        ['id_Penyakit'=>'9',  'cf'=>'0.7', 'id_Gejala'=> '1'],
        ['id_Penyakit'=>'9',  'cf'=>'0.5', 'id_Gejala'=> '2'],
        ['id_Penyakit'=>'9',  'cf'=>'0.5', 'id_Gejala'=> '3'],
        ['id_Penyakit'=>'9',  'cf'=>'0.5', 'id_Gejala'=> '4'],
        ['id_Penyakit'=>'9',  'cf'=>'0.4', 'id_Gejala'=> '9'],
        ['id_Penyakit'=>'9',  'cf'=>'0.9', 'id_Gejala'=> '16'],
        ['id_Penyakit'=>'9',  'cf'=>'0.9', 'id_Gejala'=> '21'],
        ['id_Penyakit'=>'10', 'cf'=>'0.1',  'id_Gejala'=> '1'],
        ['id_Penyakit'=>'10', 'cf'=>'0.3',  'id_Gejala'=> '4'],
        ['id_Penyakit'=>'10', 'cf'=>'0.6',  'id_Gejala'=> '9'],
        ['id_Penyakit'=>'10', 'cf'=>'0.9',  'id_Gejala'=> '21'],
        ['id_Penyakit'=>'10', 'cf'=>'0.6',  'id_Gejala'=> '22'],
        ['id_Penyakit'=>'10', 'cf'=>'0.8',  'id_Gejala'=> '23'],
        ['id_Penyakit'=>'10', 'cf'=>'0.6',  'id_Gejala'=> '24'],
        ['id_Penyakit'=>'10', 'cf'=>'0.9',  'id_Gejala'=> '25'],
        
    ];
    public function run()
    {
            
        foreach (self::$data as $data) {
            $this->db->table('rule')->insert($data);
        }

    }
}